### ISSUE TITLE
Example of emulator and dev-wallet?

### ISSUE THREAD

**Issue by fubz** [muttoni/fcl-nextjs-quickstart#1]
I'd love to see an example integrated with the emulator and dev-wallet.  I can't for the life of me get them hooked up into a dev environment.  Even the Kitty-items example is unable to connect to the dev api.

**Comment by muttoni** [comment]
Sure thing, I'll work on it asap. In the meantime you can use the Flow CLI to setup the emulator and wallet like so:

`flow project start-emulator ./flow.json --dev-wallet`

Then change the endpoints in the config.js :)

**Comment by fubz** [comment]
Wow the cli worked much better than the docker version of emulator and dev-wallet.  I created a PR; however, I am not 100% happy with it.  The Profile contract doesn't seem to auto deploy upon starting the emulator.  I'm not sure if I missed something or my understanding is incorrect.

https://github.com/muttoni/fcl-nextjs-quickstart/pull/2

**Comment by muttoni** [comment]
Thanks for your contribution @fubz - I think we can safely close this issue now that you addressed this in your latest PR, unless you have other things you want to add :)
